<?php
/**
 * UserPreferencesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EC\CNS\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CNS REST-API
 *
 * Version v1.2.0 of Corporate Notification System (CNS) REST API.
 *
 * The version of the OpenAPI document: v1.2.0
 * Contact: DIGIT-CNS-SUPPORT@ec.europa.eu
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EC\CNS\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EC\CNS\Client\ApiException;
use EC\CNS\Client\Configuration;
use EC\CNS\Client\HeaderSelector;
use EC\CNS\Client\ObjectSerializer;

/**
 * UserPreferencesApi Class Doc Comment
 *
 * @category Class
 * @package  EC\CNS\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserPreferencesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUserPreferences
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     *
     * @throws \EC\CNS\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EC\CNS\Client\Model\UserPreferences|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse
     */
    public function getUserPreferences($client_system_key, $client_system_password, $email)
    {
        list($response) = $this->getUserPreferencesWithHttpInfo($client_system_key, $client_system_password, $email);
        return $response;
    }

    /**
     * Operation getUserPreferencesWithHttpInfo
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     *
     * @throws \EC\CNS\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EC\CNS\Client\Model\UserPreferences|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserPreferencesWithHttpInfo($client_system_key, $client_system_password, $email)
    {
        $request = $this->getUserPreferencesRequest($client_system_key, $client_system_password, $email);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
            
                case 200:
                    if ('\EC\CNS\Client\Model\UserPreferences' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\UserPreferences' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\UserPreferences', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 400:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 401:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 500:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            }

            $returnType = '\EC\CNS\Client\Model\UserPreferences';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\UserPreferences',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            }
            throw $e;
        }
    }

    /**
     * Operation getUserPreferencesAsync
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPreferencesAsync($client_system_key, $client_system_password, $email)
    {
        return $this->getUserPreferencesAsyncWithHttpInfo($client_system_key, $client_system_password, $email)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserPreferencesAsyncWithHttpInfo
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPreferencesAsyncWithHttpInfo($client_system_key, $client_system_password, $email)
    {
        $returnType = '\EC\CNS\Client\Model\UserPreferences';
        $request = $this->getUserPreferencesRequest($client_system_key, $client_system_password, $email);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserPreferences'
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserPreferencesRequest($client_system_key, $client_system_password, $email)
    {

        // verify the required parameter 'client_system_key' is set
        if ($client_system_key === null || (is_array($client_system_key) && count($client_system_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_system_key when calling getUserPreferences'
            );
        }

        // verify the required parameter 'client_system_password' is set
        if ($client_system_password === null || (is_array($client_system_password) && count($client_system_password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_system_password when calling getUserPreferences'
            );
        }

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling getUserPreferences'
            );
        }

        $resourcePath = '/v1/users/{email}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_system_key,
            'clientSystemKey', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_system_password,
            'clientSystemPassword', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($email !== null) {
            $resourcePath = str_replace(
                '{' . 'email' . '}',
                ObjectSerializer::toPathValue($email),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation savePreferences
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     * @param  \EC\CNS\Client\Model\NotificationGroupPreferences[] $notification_group_preferences Submitted groups. (required)
     * @param  string $authorization EuLogin OpenId Acces token sent as \&quot;Bearer AT...\&quot; . Mandatory if ecasTicket is not present. (optional)
     * @param  string $ecas_ticket ECAS Ticket. Mandatory if header accessToken is not present. (optional)
     * @param  string $ecas_environment On which ECAS will be ticket validated (accepted values are ACC or PROD). (optional)
     *
     * @throws \EC\CNS\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EC\CNS\Client\Model\SuccessfulResult|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse
     */
    public function savePreferences($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization = null, $ecas_ticket = null, $ecas_environment = null)
    {
        list($response) = $this->savePreferencesWithHttpInfo($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization, $ecas_ticket, $ecas_environment);
        return $response;
    }

    /**
     * Operation savePreferencesWithHttpInfo
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     * @param  \EC\CNS\Client\Model\NotificationGroupPreferences[] $notification_group_preferences Submitted groups. (required)
     * @param  string $authorization EuLogin OpenId Acces token sent as \&quot;Bearer AT...\&quot; . Mandatory if ecasTicket is not present. (optional)
     * @param  string $ecas_ticket ECAS Ticket. Mandatory if header accessToken is not present. (optional)
     * @param  string $ecas_environment On which ECAS will be ticket validated (accepted values are ACC or PROD). (optional)
     *
     * @throws \EC\CNS\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EC\CNS\Client\Model\SuccessfulResult|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse|\EC\CNS\Client\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function savePreferencesWithHttpInfo($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization = null, $ecas_ticket = null, $ecas_environment = null)
    {
        $request = $this->savePreferencesRequest($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization, $ecas_ticket, $ecas_environment);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
            
                case 200:
                    if ('\EC\CNS\Client\Model\SuccessfulResult' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\SuccessfulResult' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\SuccessfulResult', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 400:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 401:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            
                case 500:
                    if ('\EC\CNS\Client\Model\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EC\CNS\Client\Model\ErrorResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EC\CNS\Client\Model\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            
            }

            $returnType = '\EC\CNS\Client\Model\SuccessfulResult';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\SuccessfulResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EC\CNS\Client\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            
            }
            throw $e;
        }
    }

    /**
     * Operation savePreferencesAsync
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     * @param  \EC\CNS\Client\Model\NotificationGroupPreferences[] $notification_group_preferences Submitted groups. (required)
     * @param  string $authorization EuLogin OpenId Acces token sent as \&quot;Bearer AT...\&quot; . Mandatory if ecasTicket is not present. (optional)
     * @param  string $ecas_ticket ECAS Ticket. Mandatory if header accessToken is not present. (optional)
     * @param  string $ecas_environment On which ECAS will be ticket validated (accepted values are ACC or PROD). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function savePreferencesAsync($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization = null, $ecas_ticket = null, $ecas_environment = null)
    {
        return $this->savePreferencesAsyncWithHttpInfo($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization, $ecas_ticket, $ecas_environment)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation savePreferencesAsyncWithHttpInfo
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     * @param  \EC\CNS\Client\Model\NotificationGroupPreferences[] $notification_group_preferences Submitted groups. (required)
     * @param  string $authorization EuLogin OpenId Acces token sent as \&quot;Bearer AT...\&quot; . Mandatory if ecasTicket is not present. (optional)
     * @param  string $ecas_ticket ECAS Ticket. Mandatory if header accessToken is not present. (optional)
     * @param  string $ecas_environment On which ECAS will be ticket validated (accepted values are ACC or PROD). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function savePreferencesAsyncWithHttpInfo($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization = null, $ecas_ticket = null, $ecas_environment = null)
    {
        $returnType = '\EC\CNS\Client\Model\SuccessfulResult';
        $request = $this->savePreferencesRequest($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization, $ecas_ticket, $ecas_environment);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'savePreferences'
     *
     * @param  string $client_system_key The unique client system key identifier. (required)
     * @param  string $client_system_password Client System Password. (required)
     * @param  string $email User Email. (required)
     * @param  \EC\CNS\Client\Model\NotificationGroupPreferences[] $notification_group_preferences Submitted groups. (required)
     * @param  string $authorization EuLogin OpenId Acces token sent as \&quot;Bearer AT...\&quot; . Mandatory if ecasTicket is not present. (optional)
     * @param  string $ecas_ticket ECAS Ticket. Mandatory if header accessToken is not present. (optional)
     * @param  string $ecas_environment On which ECAS will be ticket validated (accepted values are ACC or PROD). (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function savePreferencesRequest($client_system_key, $client_system_password, $email, $notification_group_preferences, $authorization = null, $ecas_ticket = null, $ecas_environment = null)
    {

        // verify the required parameter 'client_system_key' is set
        if ($client_system_key === null || (is_array($client_system_key) && count($client_system_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_system_key when calling savePreferences'
            );
        }

        // verify the required parameter 'client_system_password' is set
        if ($client_system_password === null || (is_array($client_system_password) && count($client_system_password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $client_system_password when calling savePreferences'
            );
        }

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling savePreferences'
            );
        }

        // verify the required parameter 'notification_group_preferences' is set
        if ($notification_group_preferences === null || (is_array($notification_group_preferences) && count($notification_group_preferences) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $notification_group_preferences when calling savePreferences'
            );
        }




        $resourcePath = '/v1/users/{email}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_system_key,
            'clientSystemKey', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $client_system_password,
            'clientSystemPassword', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ecas_ticket,
            'ecasTicket', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ecas_environment,
            'ecasEnvironment', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($email !== null) {
            $resourcePath = str_replace(
                '{' . 'email' . '}',
                ObjectSerializer::toPathValue($email),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($notification_group_preferences)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($notification_group_preferences));
            } else {
                $httpBody = $notification_group_preferences;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
